name: release

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env: 
      REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      # Build and push with docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure tags based on git tags + latest
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=pep440,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=pr

      - name: Docker login on main origin
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: REPOSITORY=${{ env.REPOSITORY }}

